---
- hosts: check_point
  connection: httpapi

  tasks:
    - name: show-simple-gateways
      cp_mgmt_simple_gateway_facts:
        details_level: full
      register: result_1 

    - name: output results
      copy:
        content: "{{ result_1 | to_nice_json }}"
        dest: "sample_result/show_simple_gateways_{{ inventory_hostname | replace('.', '_') }}.json"