---
- name: playbook name
  hosts: check_point
  connection: httpapi
  tasks:

    #Get access-role objects facts on Check Point over Web Services API
    - name: show-access-roles
      cp_mgmt_access_role_facts:
        name:
        details_level: full
      register: result
        
    # - name: debug
    #   debug: 
    #     msg: "{{ result }} "

    - name: output results
      copy:
        content: "{{ result | to_nice_json }}"
        dest: "sample_result/show_access_roles_{{ inventory_hostname | replace('.','_') }}.json" 