---
- name: playbook name
  hosts: check_point
  connection: httpapi
  tasks:

    #Get administrator objects facts on Checkpoint over Web Services API
    - name: show-administrators
      cp_mgmt_administrator_facts:
        details_level: standard
        limit: 50
        offset: 0
      register: result
        
    # - name: debug
    #   debug: 
    #     msg: "{{ result }} "

    - name: output results
      copy:
        content: "{{ result | to_nice_json }}"
        dest: "sample_result/show-administrators_{{ inventory_hostname | replace('.','_') }}.json" 